[book]
authors = ["xinglongjian"]
language = "zh"
description = "This is MICI TECH STACK Official Documents."
multilingual = false
src = "src"
title = "幂次小栈官方文档"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/micitechstackoffical/mici"
edit-url-template = "https://github.com/micitechstackoffical/mici/edit/main/{path}"
site-url = "/mici/"

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = true          # displays a run button for rust code